version: '3.8'
services:
  db:
    container_name: pg-alpine
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.local
    networks:
      - local

networks:
  local:
    driver: bridge
